using FluentMigrator;

namespace CongratulateApi.DataAccess.Migrations;

[Migration(20240721130100, TransactionBehavior.None, "Initial migration")]
public class InitSchema : Migration
{
    public override void Up()
    {
        String createPeopleTable = @"
        create table if not exists people (
            id bigint primary key generated by default as identity,
            name text not null,
            surname text not null,
            day_of_birth date not null,
            photo_id text,
            photo_url text        
        );";
        Execute.Sql(createPeopleTable);
    }

    public override void Down()
    {
        Delete.Table("people").IfExists();
    }
}